### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by soorajnraju** [WPoets/linkedin-handler#1]
While we use the LinkedIn service for authentication, we are getting a 404 from LinkedIn because the endpoint got changed and it's not updated in the composer package that we are using.

https://github.com/zoonman/linkedin-api-php-client

**Comment by thecancerus** [comment]
An update of linedin-api library has not been released for a while.

**Comment by soorajnraju** [comment]
This issue is resolved by changing the composer package
